### ISSUE TITLE
v1.3.0 exited before replying to getmanifest

### ISSUE THREAD

**Issue by pabpas** [daywalker90/summars#1]
Until version 1.2.1 I have been enjoying this plugin without issues. Upgrading to 1.3.0 throws the following error when starting:

```
$ lightning-cli plugin start summars/summars
{
   "code": -3,
   "message": "/home/lightning/summars-v1.3.0/summars: exited before replying to getmanifest"
}
```
```
$ lightning-cli getinfo
"version": "v23.08.1"
```

**Comment by daywalker90** [comment]
Thats very unusual.

- Did you compile it yourself or used the release binaries?
- Can you provide more logs from lightningd?

**Comment by daywalker90** [comment]
Also this command: `lightning-cli plugin start summars/summars` does not seem correct when looking at the response where the actual binary is. Can you try `lightning-cli plugin start /home/lightning/summars-v1.3.0/summars` ?

**Comment by pabpas** [comment]
I just found the issue. I was trying to run the release binaries and seems that 1.3.0 needs glibc >=2.32 and this machine is still running debian oldstable which uses glibc 2.31.
Time for me to stop delaying the upgrade to bookworm.
```
/summars-v1.3.0/summars: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/lightning/summars-v1.3.>
/summars-v1.3.0/summars: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/lightning/summars-v1.3.>
/summars-v1.3.0/summars: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/lightning/summars-v1.3.>
```
Thank you for the quick reply and for the great plugin.

**Comment by daywalker90** [comment]
ah forgot about that, i should add a hint for that requirement when using release binaries. You should still be able to build it yourself though. Thanks for the feedback!
