### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by Sjors** [daywalker90/summars#10]
Currently the date format uses a US locale:

```
3/17/24, 1:45:00 PM
```

Can you make it follow the system locale? E.g. for `ls -al` times are formatted `Mar  4 11:46`

A custom formatter would be fine as well (e.g. I like the Chinese format `2024/03/04 13:45:00`)

**Comment by daywalker90** [comment]
Ah i forgot to update the README. Since v3.0.0 summars-locale (e.g. `summars-locale=ch`) is working for all number and date formatting. It defaults to system locale with a fallback to en-US. Could you tell me your output of something like `locale -a`, i don't know why it's not using your system default.

**Comment by Sjors** [comment]
```
$ locale -a
C
C.utf8
POSIX
```

Mmm, that doesn't say NL anywhere.

**Comment by Sjors** [comment]
`summars-locale=nl` does the trick though, so I would just add that to the README

**Comment by daywalker90** [comment]
> `summars-locale=nl` does the trick though, so I would just add that to the README

done

> ```
> $ locale -a
> C
> C.utf8
> POSIX
> ```
> 
> Mmm, that doesn't say NL anywhere.

Detecting the systems locale is very difficult it seems. Check `locale` and see what `LC_ALL` -> `LC_CTYPE` -> `LANG` are set to (that's the priority list of envs that get checked). BUT keep in mind that if you started cln with systemd it has it's own environment and you would have to set e.g. `Environment="LC_ALL=en_US.UTF-8"` in your service file. All very complicated and so i would just use `summars-locale=nl` in your case.

**Comment by Sjors** [comment]
I indeed start c-lightning with systemd (though I manually started the plugin for this testing), so I agree that using the `summars-locale` config makes more sense.

**Comment by Sjors** [comment]
(I didn't test c73633aa0af673b920308eeab93df683046f28e6)
