### ISSUE TITLE
rpc return the response in json

### ISSUE THREAD

**Issue by vincenzopalazzo** [daywalker90/summars#11]
The information exposed by the plugin is super useful also for other plugins, but the information should be in a structured format.

Do you think that will be possible to have a way to return from the json rpc method json format? or it is too hard

P.S: I did not look inside the code yet, maybe it is a stupid question

**Comment by daywalker90** [comment]
please give this branch a try
https://github.com/daywalker90/summars/tree/json-output

use the option `summars-json=true`

**Comment by vincenzopalazzo** [comment]
I will, thanks!
   Vincent.

**Comment by daywalker90** [comment]
i have released it with v3.2.0, if you have an issue with the json output please open another issue
