### ISSUE TITLE
Can we drop `PEER_ID` from default columns?

### ISSUE THREAD

**Issue by RCasatta** [daywalker90/summars#15]
Undoubtedly it is a useful info, but it's very long and makes the summary not staying on one line even in pretty big screens

**Comment by daywalker90** [comment]
The goal when i wrote this plugin was: get a quick glance on what's going on and then issue one command to get more info on something. To get more info on a channel CLN requires the peer_id. So i think it should stay. On my screen the default columns fit the screen in one line 😄 . I'd rather remove some other columns from the default instead.

**Comment by RCasatta** [comment]
Usually the `scid` works too?

Anyway I don't want to push anything, the tool is great, I just want to provide some feedbacks

**Comment by daywalker90** [comment]
No, listpeerchannels only takes node ids
