### ISSUE TITLE
Useful columns

### ISSUE THREAD

**Issue by RCasatta** [daywalker90/summars#16]
Just another feedback: 
Columns I would personally find useful:

- [ ] TOT_SATS (IN_SATS+OUT_SATS)
- [ ] THEIR_PPM
- [ ] THEIR_BASE
- [ ] MIN_HTLC

**Comment by daywalker90** [comment]
I've added `TOTAL_SATS`, `IN_PPM`, `IN_BASE` and `MIN_HTLC` to the main branch.

**Comment by RCasatta** [comment]
Just tried out, looks great, thanks!

p.s. just tried to tip you on the bolt12 in coffee.yml and the payment failed

**Comment by daywalker90** [comment]
> p.s. just tried to tip you on the bolt12 in coffee.yml and the payment failed

Thanks! I've received to these before successfully, can you provide more info?

**Comment by RCasatta** [comment]
![Screenshot_20240708-154047.png](https://github.com/daywalker90/summars/assets/6470319/919714b8-901c-4393-b47e-23aa6fb9e3b6)

**Comment by daywalker90** [comment]
What wallet is that? There are still some cross compatibility issues with bolt12 right now

**Comment by RCasatta** [comment]
it's phoenix, the strange thing is that it worked 4 days ago (I sent you with desc "thanks for your core lightning plugins")

**Comment by daywalker90** [comment]
ah thanks! hmm i didn't change anything inbetween. Feel free to use this bolt11 in the meantime 😄 
```
lnbc190290n1pnghmd7sp5249a9ykg06lguva9nlayr8m3q2g5u05yhaxlmn5xxv6p2reteswspp5jnduyttuhp7qa3j4wxcmrt24u0a4ep2vxnwxgsrsuh6p8h5y0xrqdp9wd6k6mtpwfejqarfwqsxy7fqwf3kzumpw36xzxqyjw5qcqpjrzjq2l7ja0trzefg40wd4wr5twxeqyhedxe5w8mgsx768jxfveuej0kqrrp2uqqtpsqpgqqqqlgqqqqqqgq2q9qxpqysgqztlrpfpf3dcdhzdjdm6kt9nefjp29ech2ew5ygezysqgq0a8etz4aw2prv023npfycewy3lw0dj089fktj7sm8683n58na09ze7htxqpcrfzm2
```
![rcasatta](https://github.com/daywalker90/summars/assets/8257956/c2d93827-ba72-402f-b648-196b80391afc)

**Comment by RCasatta** [comment]
I went ahead with cln using the bolt12, you should have received it

**Comment by daywalker90** [comment]
Yes, thank you!
