### ISSUE TITLE
be able to calculate the total amount pays over a period of time

### ISSUE THREAD

**Issue by vincenzopalazzo** [daywalker90/summars#18]
I am using summars, but I would like to have a command that will return to me the tot amount of sats that I paid over a period.

A possible idea would be `lightning-cli summars summars-sats-paid=8760`

I do not know if it is so easy, but would be good to have a way to divided the amount sent, and the routing fee paid, e.g: the following command

```
lightning-cli summars summars-pays=8760 --summars-json=true
{
  "amount_sats_send": 10000000,
  "amount_tot_sats_send": 10000020,
}
```

Where `amount_tot_sats_send - amount_sats_send` = routing fee.

Are you interested in adding this functionality to the plugin? looks like that we do not have anything that will show this information

**Comment by daywalker90** [comment]
Yes, i wanted to do this for forwards, might aswell do it for invoices and pays aswell. As to how exactly i'll integrate this i'm not sure yet. Either like you wrote as a separate command or right into the summars command itself.

**Comment by vincenzopalazzo** [comment]
>Either like you wrote as a separate command or right into the summars command itself.

I like the idea of "total amount sent" inside the `summars` command, however, I feel that it is necessary to have a separate command, to answer questions like "How much did I spend in the last 50 days?"

What do you think?

**Comment by daywalker90** [comment]
I could definitely just put it in the summars command with an extra return object when its json. Something like

```json
"totals": {
    "pays_amount_sent_msat": 5000,
    "pays_amount_total_sent_msat": 5050,
    "pays_fees_msat": 50,
    "invoices_amount_received_msat": 10000,
    "forwards_amount_in_msat": 4000,
    "forwards_amount_out_msat": 3850,
    "forwards_fees_msat": 150,
}
```

I'd like to avoid creating an extra rpc method for each of these. Or is your issue about the unit of the option "summars-pays"? Would you like to see a "summars-pays-days" ?

**Comment by vincenzopalazzo** [comment]
>Would you like to see a "summars-pays-days" ?

At the accounting level this kind of command would be good, currently, all the cln plugins (including web UI) do monkey things. I am wondering how people do accounting in production?

For the totals value, I like your idea of putting everything in a totals object

**Comment by daywalker90** [comment]
New `totals` object/output in summars v3.5.0. I have decided against `summars-x-days` for now since i think the complexity and clutter is not worth the convenience of calculating `*24`

**Comment by vincenzopalazzo** [comment]
>I have decided against summars-x-days for now since i think the complexity and clutter is not worth the convenience of calculating *24

I see, thanks! if this is really needed I will write that code, but for now the total is fine for me, thanks
