### ISSUE TITLE
Feature request: Ability to not show "channels" with state ONCHAIN

### ISSUE THREAD

**Issue by tsjk** [daywalker90/summars#2]
Sometimes cln takes very long time to forget a channel, and there are even scenarios where they aren't forgotten until cln is restarted. The latter case is likely a bug. But regardless, being able to exclude states in general - most importantly the ONCHAIN state in particular - would be nice.

**Comment by daywalker90** [comment]
Would you expect the summary at the top (`num_channels`, `avail_out` etc.) to be always the same, independent of the excluded channels? Or would you expect the summary at the top to be about the actual shown channels?

**Comment by tsjk** [comment]
There is a possibility to exclude private channels in the original summary plugin. When one does that, the stats are adjusted accordingly. I'd think this makes sense, especially for channels that have state ONCHAIN. Those shouldn't be counted as contributing to `avail_out`/`avail_in` - especially when excluded. Imho.

**Comment by daywalker90** [comment]
Only channels that are in `OK` or `AWAIT_SPLICE` are counted towards `avail_x` values already. I could mix in a `PRIVATE` state in addition to the other states. I'll also add a line that says how many channels are filtered to make it more clear that the stats are for the unfiltered.

**Comment by daywalker90** [comment]
fixed in #4
