### ISSUE TITLE
Error when using summars-forwards

### ISSUE THREAD

**Issue by GamerSg** [daywalker90/summars#7]
I built the plugin from source and tried using it. The default summars command works fine. But when i use 
Note: lncli is an alias i have setup for myself to call lightning-cli with the appropriate --lightning-dir

lncli summars -k summars-forwards=10
"Error calling list_forwards: Error code -32602: unknown parameter: index, this may be caused by a failure to autodetect key=value-style parameters. Please try using the -k flag and explicit key=value pairs of parameters."

**Comment by daywalker90** [comment]
Try it without -k, i'll look into why it does not like -k

**Comment by GamerSg** [comment]
I tried without -k as well, same result.
Im running this on a rasbpi4 if that matters.

**Comment by daywalker90** [comment]
maybe your alias already contains a -k ?

**Comment by daywalker90** [comment]
Sorry, i should have read your error message more closely. The error is from something entirely different. It is because you cln version is too old. You need ATLEAST 23.11 for the newest summars, or go back to summars 1.3.2.

**Comment by Sjors** [comment]
I'm also getting a failure when `summars-forwards` is set:

```
"Error calling list_forwards: Error: Failed to deserialize response : missing field `received_time`"
```

Perhaps because the installation is fresh and no forwards happen yet?

I configured with:
```
summars-forwards=24
summars-pays=24
summars-invoices=24
```

It works once I drop `summars-forwards`.

Running c-lightning v24.02.1, and the plugin built from source at v3.1.0

This might be a different issue though, I'll open a new issue: #9
