### ISSUE TITLE
How to reverse sort

### ISSUE THREAD

**Issue by Sjors** [daywalker90/summars#8]
I'd like to sort such that the largest outbound capacity is at the top.

```
lightning-cli summars summars-columns=ALIAS,GRAPH_SATS summars-sort-by=-OUT_SATS
"Not a valid column name: `-OUT_SATS`.
```

**Comment by daywalker90** [comment]
There is currently no way to reverse sort, sorry. But i thought about this a little already. You think using a `-` before the name is a good idea? I like it.

**Comment by daywalker90** [comment]
You can try this now if you build [main](https://github.com/daywalker90/summars/tree/main)

**Comment by Sjors** [comment]
Works!
